version: "3.7"
services:
  app:
    image: autogpt
    hostname: autogpt
    restart: always
    init: true
    stop_grace_period: 1m
    tty: true
    environment:
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENV=${PINECONE_ENV}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - ELEVENLABS_VOICE_1_ID=${ELEVENLABS_VOICE_1_ID}
      - ELEVENLABS_VOICE_2_ID=${ELEVENLABS_VOICE_2_ID}
      - SMART_LLM_MODEL=${SMART_LLM_MODEL}
      - FAST_LLM_MODEL=${FAST_LLM_MODEL}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - CUSTOM_SEARCH_ENGINE_ID=${CUSTOM_SEARCH_ENGINE_ID}
      - USE_AZURE=${USE_AZURE}
      - OPENAI_AZURE_API_BASE=${OPENAI_AZURE_API_BASE}
      - OPENAI_AZURE_API_VERSION=${OPENAI_AZURE_API_VERSION}
      - OPENAI_AZURE_DEPLOYMENT_ID=${OPENAI_AZURE_DEPLOYMENT_ID}
      - IMAGE_PROVIDER=${IMAGE_PROVIDER}
      - HUGGINGFACE_API_TOKEN=${HUGGINGFACE_API_TOKEN}
      - USE_MAC_OS_TTS=${USE_MAC_OS_TTS}
      - MEMORY_BACKEND=${MEMORY_BACKEND}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - WIPE_REDIS_ON_START=${WIPE_REDIS_ON_START}
      - EXECUTE_LOCAL_COMMANDS=${EXECUTE_LOCAL_COMMANDS}
      - RESTRICT_TO_WORKSPACE=${RESTRICT_TO_WORKSPACE}
      - RAPID_API_KEY=${RAPID_API_KEY}
      - U_COOKIE=${U_COOKIE}
    ports:
      - '8080:8080'
