version: "3.7"
services:
  app:
    build:
      context: ./docker/autogpt
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    image: tvup/autogpt-gotty
    hostname: autogpt
    restart: on-failure
    init: true
    stop_grace_period: 1m
    tty: true
    networks:
      - autogpt
    volumes:
      - ${PWD}/workspace/:/app/auto_gpt_workspace/
      - ${PWD}/logs/:/logs/
      - type: bind
        source: ${PWD}/.env
        target: /app/.env
        read_only: true
      - type: bind
        source: ${PWD}/ai_settings.yaml
        target: /app/ai_settings.yaml
        read_only: false
      - type: bind
        source: ${PWD}/auto-gpt.json
        target: /app/auto-gpt.json
        read_only: false
    depends_on:
      - redis-stack-server
    environment:
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
    ports:
      - '${FORWARD_APP_PORT:-8080}:8080'
  redis-stack-server:
    image: redis/redis-stack-server:latest
    networks:
      - autogpt
    ports:
      - '127.0.0.1:${FORWARD_REDIS_PORT:-6379}:6379'
    command: [ "redis-stack-server", "--requirepass", "${REDIS_PASSWORD}" ]
    volumes:
      - redis-data:/data

networks:
  autogpt:
volumes:
  redis-data:
    driver: local
