kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "autogpt-app.fullname" . }}-configs
data:
  COMMAND_LINE_PARAMS: '--install-plugin-deps'
  ELEVENLABS_API_KEY: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  ELEVENLABS_VOICE_ID: xxxx
  EXECUTE_LOCAL_COMMANDS: 'True'
  FAST_LLM_MODEL: gpt-3.5-turbo
  IMAGE_PROVIDER: dalle
  MEMORY_BACKEND: json_file
  REDIS_HOST: redis-stack-server
  REDIS_PASSWORD: ''
  REDIS_PORT: '6379'
  RESTRICT_TO_WORKSPACE: 'False'
  SMART_LLM_MODEL: gpt-4
  USE_AZURE: 'False'
  WIPE_REDIS_ON_START: 'False'
