apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autogpt-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: do-block-storage-retain
