{{- range $pvc := .Values.persistentVolumeClaims }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "autogpt-app.fullname" $ }}-{{ $pvc.name }}-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $pvc.size }}
  storageClassName: {{ $pvc.storageClassName }}
  persistentVolumeReclaimPolicy: Delete
{{- end }}
