apiVersion: v1
kind: Service
metadata:
  name: {{ include "autogpt-app.fullname" . }}
  labels:
    {{- include "autogpt-app.labels" . | nindent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/access: private
    external-dns.alpha.kubernetes.io/ttl: '30'
    kubernetes.digitalocean.com/firewall-managed: 'false'
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodeport }}
  selector:
    {{- include "autogpt-app.selectorLabels" . | nindent 4 }}
